'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class yourPELEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=yourPELEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property POST() As DbSet(Of POST)
    Public Overridable Property RESPOSTA() As DbSet(Of RESPOSTA)
    Public Overridable Property UTILIZADOR() As DbSet(Of UTILIZADOR)

End Class
