'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class POST
    Public Property ID_POST As Integer
    Public Property TITULO As String
    Public Property TEXTO As String
    Public Property DATA_HORA As String
    Public Property TEMA As String
    Public Property ATIVO As Boolean
    Public Property FECHADO As Nullable(Of Boolean)

End Class
Partial Public Class RESPOSTA
    Public Property ID_RESPOSTA As Integer
    Public Property TEXTO As String
    Public Property DATA_HORA As Date
    Public Property ID_UTILIZADOR As Integer
    Public Property ID_POST As Integer

End Class
Partial Public Class UTILIZADOR
    Public Property ID_UTILIZADOR As Integer
    Public Property USERNAME As String
    Public Property PASSWORD As String
    Public Property TIPO As String

End Class
